version: "3"
services:
    web:
        build:
            context: ./
            dockerfile: Minimal/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "Chukwujekwu_1996"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"